# Generated by Django 2.0.5 on 2018-05-21 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_auto_20180518_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='label',
            name='bag_size',
        ),
        migrations.AddField(
            model_name='label',
            name='addon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='labels.Addon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='bag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='labels.Bag'),
            preserve_default=False,
        ),
    ]
