# Generated by Django 2.0.5 on 2018-05-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_auto_20180521_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='short_title',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
