# Generated by Django 2.0.5 on 2018-05-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_addon_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
