# Generated by Django 2.0.5 on 2018-05-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0006_auto_20180521_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='addon',
        ),
        migrations.DeleteModel(
            name='Addon',
        ),
    ]
