# Generated by Django 2.0.5 on 2018-05-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0007_auto_20180521_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='short_title',
        ),
        migrations.AddField(
            model_name='label',
            name='long_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
