# Generated by Django 2.0.5 on 2018-05-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0008_auto_20180521_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='long_title',
        ),
        migrations.AddField(
            model_name='label',
            name='header',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
